staticSites:
  - type: web
    name: IntelliChat-frontend
    buildCommand: npm install && npm run build
    publishPath: frontend/dist
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
